name: Sign APK
on:
  workflow_dispatch:   # manual run button
  push:
    tags: [ "v*" ]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Download the APK that is already in your repo
      - name: Fetch APK
        run: |
          curl -L \
          https://github.com/Harlonge64-eng/chiride-taxis-apk/releases/download/v1.0.0/_Chiride_Taxis_Apk.apk \
          -o unsigned.apk

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: chiride
          keyStorePassword: android
          keyPassword: android

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChirideTaxis-signed
          path: unsigned-signed.apk
