name: Sign APK
on:
  workflow_dispatch:   # manual run
  push:
    tags: [ "v*" ]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download APK
        run: |
          curl -L \
          https://github.com/Harlonge64-eng/chiride-taxis-apk/releases/download/v1.0.0/_Chiride_Taxis_Apk.apk \
          -o unsigned.apk

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Sign APK
        run: |
          # fetch the lightweight signer
          curl -L https://github.com/topjohnwu/signapk/releases/download/1.0/signapk.jar -o signapk.jar
          # create test keys locally
          openssl genrsa -out key.pk8 2048
          openssl req -new -x509 -key key.pk8 -out cert.pem -subj "/CN=chiride" -days 3650
          # sign
          java -jar signapk.jar cert.pem key.pk8 unsigned.apk signed.apk

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChirideTaxis-signed
          path: signed.apk
